DATA:
  images_dir: "C:\\Users\\Alex\\Documents\\projects\\reefs\\train_images"
  gt_path: "C:\\Users\\Alex\\Documents\\projects\\reefs\\train.csv"
  visualize_dir: "C:\\Users\\Alex\\Documents\\projects\\reefs\\vis"
